apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.configMap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  {{- range $key, $value := .Values.app.configMap.values }}
    {{ $key }}: "{{ $value }}"
  {{- end }}