apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    {{ .Values.app.label.first }}: {{ .Values.app.label.second }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}