apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.nginx.service.type }}
  selector:
    {{ .Values.nginx.label.first }}: {{ .Values.nginx.label.second }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.port }}
